# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoggieDuty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoggieDuty
  pod "Parse"
  pod "AlamofireImage"

  target 'DoggieDutyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DoggieDutyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
